### ISSUE TITLE
SLAC production code is not under version control

### ISSUE THREAD

**Issue by drphilmarshall** [eggplantbren/TimeBombs#1]
@rumbaugh you might need to make the code and its Makefile a little more flexible. You can always check for an environment variable called "LOCATION" that you insist be set.

**Comment by rumbaugh** [comment]
I've got TimeBombs version-controlled on the SLAC computers, but I tested it and it's giving weird output, so I need to figure out what went wrong.

**Comment by rumbaugh** [comment]
Okay, I fixed the problems, which were with the script I made to call TimeBombs. I tested it on some data and it is giving similar results to previous runs.

**Comment by drphilmarshall** [comment]
Good work, @rumbaugh! Now you can seamlessly take advantage of improvements
that you and @eggplantbren make.
