### ISSUE TITLE
Model description

### ISSUE THREAD

**Issue by drphilmarshall** [eggplantbren/TimeBombs#3]
We need one. What is the functional form of the flares? What prior PDFs are assumed for their parameters? What are the flare hyper-parameters? We need this all written down in latex. Do you have this to hand, @eggplantbren? I made a "paper" directory but didn't put a latex file in it. I'll issue that too!

**Comment by eggplantbren** [comment]
I'm happy to do this some time soon, but I propose we also merge in changes that we made in dhuppenkothen/magnetronhierarchy, which greatly improved that model (TimeBombs is a descendent of Magnetron).

**Comment by drphilmarshall** [comment]
Oh that sounds good. Can you briefly summarize those changes please? 140 chars or fewer ;-)

**Comment by eggplantbren** [comment]
Analytical integration of the spike profile over the bins, and a correlated (AR(1)) component added to the log-rate for 'robustness'

**Comment by eggplantbren** [comment]
I have almost finished doing this (merging in the latest from magnetronhierarchy) in a separate branch. Are y'all happy for me to merge it into master soon?

**Comment by drphilmarshall** [comment]
Sure! Do it by pull request and we'll be able to see the changes. Thanks
Bren!

**Comment by eggplantbren** [comment]
You can see the changes by looking at the branches on here. I doubt they'll be intelligible to anyone. I would like to do the merge: the worst possible disadvantage is that the appropriate column numbers in the output will have shifted a little.

**Comment by drphilmarshall** [comment]
OK, I see the comparison [here](https://github.com/eggplantbren/TimeBombs/compare/magnetron_merge) - @rumbaugh do you see any problems looming? I think we should do the merge and deal with it as recommended by @eggplantbren, if at all possible.

All of these files are code, though - so we cannot close this issue yet! Thanks for the new c++, Brendon.

**Comment by eggplantbren** [comment]
Done.
