### ISSUE TITLE
Rumbaugh cannot be issued with tasks until he is a collaborator

### ISSUE THREAD

**Issue by drphilmarshall** [eggplantbren/TimeBombs#5]
Will you enoble him in this way, please @eggplantbren ? His GitHub username is @narumbaugh !

**Comment by eggplantbren** [comment]
I thought it was 'rumbaugh'? Done, I think.

**Comment by drphilmarshall** [comment]
Yep! Thanks @eggplantbren. I did get Nick's name wrong, yes - he's @rumbaugh as you guessed. Actually can you add @jchiang87 as well please? I'd like to issue Jim too :-)
