### ISSUE TITLE
More blazars!

### ISSUE THREAD

**Issue by drphilmarshall** [eggplantbren/TimeBombs#7]
@jchiang87 can you check out the publically-available monitored source list please? We're after 1-day sampling or better, as many blazars as we can find, and lightcurves available in more than one energy bin, in order to train our flare model. If you can design a suitable training sample, @rumbaugh can download the data and run the no-lens model on them.

**Comment by drphilmarshall** [comment]
PS. This training sample should help us test whether our flare model is any good, as well as telling us what structure to build into the hyperprior.

**Comment by jchiang87** [comment]
The data for the Fermi Monitored source list is generated here at SLAC (by
some scripts that I wrote) before it is sent to the FSSC every morning at
7:30 PT.   I've copied the file containing all of the light curve data as
of this morning to

/nfs/farm/g/glast/u/jchiang/Lensing/TimeBombs/python/Fermi/gll_asp_0457833600_v00.fit

on slac linux.   The data are packed somewhat idiosyncratically to
facilitate transferring from our db tables to the ones they have at the
FSSC, so I've written a script to do the unpacking and checked it into my
fork of TimeBombs:

https://github.com/jchiang87/TimeBombs/blob/master/python/Fermi/FermiLightCurves.py

There is example code on how to use it near the bottom of the script, and
I've attached the plots it generates.

-Jim

On Mon, Jul 6, 2015 at 5:13 PM, Phil Marshall notifications@github.com
wrote:

> @jchiang87 https://github.com/jchiang87 can you check out the
> publically-available monitored source list please? We're after 1-day
> sampling or better, as many blazars as we can find, and lightcurves
> available in more than one energy bin, in order to train our flare model.
> If you can design a suitable training sample, @narumbaugh can download the
> data and run the no-lens model on them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eggplantbren/TimeBombs/issues/7.

## 

James Chiang       SLAC, MS 29          home:   (650) 605-3346
Fermi ISOC         2575 Sand Hill Rd    office: (650) 926-2930
                   Menlo Park CA 94025  FAX:    (650) 926-5566

**Comment by drphilmarshall** [comment]
That's cool, thanks Jim! @rumbaugh, can you please download and unpack the data using Jim's code please, and close this issue when you have convinced yourself you have the data and understand it? Any problems, just reply to this thread. You'll need to do "git pull jim master" to get his script; you can do this in your master branch no problem, I think.

**Comment by jchiang87** [comment]
BTW, the rows that have the UL (upper limit) flag set to True report the 95%CL upper limit instead of the best fit flux.  These are the red points in the FSSC plots. There is an option to filter out those values in the light_curves(...) method, but it probably would be ok to include them in the fits while we are still getting a feel for things.

**Comment by rumbaugh** [comment]
Okay, I downloaded the file and I got the python script with a git pull. I plotted up the lightcurves, but I had to use my own code because I don't have python_plotter. Is that something that is publicly available? Also, you said there would be red points plotted up for the UL points, but I don't see those in the plots you attached, or how it is dealing with them in the python script.

**Comment by jchiang87** [comment]
Hey Nick,

pylab_plotter is my own interface to matplotlib/pylab.  If you really want
it, a copy is available here:

https://github.com/lsst-camera-dh/eotest/blob/master/python/lsst/eotest/sensor/pylab_plotter.py

but it's not intended for general use.   The red points appear in the FSSC
version of those plots:

http://fermi.gsfc.nasa.gov/ssc/data/access/lat/msl_lc/source/3C_454d3

but I don't bother having that example code plot them or handle them in any
special way.  The lightcurves(...) function returns the ul array which has
the flags and would thus allow you to handle them however you like in your
own post processing.

-Jim

On Tue, Jul 7, 2015 at 2:07 PM, Nick Rumbaugh notifications@github.com
wrote:

> Okay, I downloaded the file and I got the python script with a git pull. I
> plotted up the lightcurves, but I had to use my own code because I don't
> have python_plotter. Is that something that is publicly available? Also,
> you said there would be red points plotted up for the UL points, but I
> don't see those in the plots you attached, or how it is dealing with them
> in the python script.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eggplantbren/TimeBombs/issues/7#issuecomment-119341598
> .

## 

James Chiang       SLAC, MS 29          home:   (650) 605-3346
Fermi ISOC         2575 Sand Hill Rd    office: (650) 926-2930
                   Menlo Park CA 94025  FAX:    (650) 926-5566

**Comment by rumbaugh** [comment]
Oh, okay. I thought I was missing something since I didn't see any red points in those plots.
